/**
 * Runtime configuration loaded from runtime-config.json
 * Generated by run_osrm.sh before starting the backend.
 */
let RUNTIME_CONFIG = {
  displayProfile: "driving",
  tdEnabled: false,
};

/**
 * Load runtime configuration from runtime-config.json
 */
async function loadRuntimeConfig() {
  try {
    const response = await fetch("/runtime-config.json?t=" + Date.now());
    if (response.ok) {
      RUNTIME_CONFIG = await response.json();
      console.log("Runtime config loaded:", RUNTIME_CONFIG);
    } else {
      console.warn("runtime-config.json not found, using defaults");
    }
  } catch (error) {
    console.warn("Could not load runtime-config.json:", error.message);
  }
}

/**
 * Main application entry point
 */
document.addEventListener("DOMContentLoaded", async function () {
  // Load runtime config first (profile name, TD enabled/disabled)
  await loadRuntimeConfig();

  // Initialize components
  initBackendSettings(); // Initialize backend URL first
  initMap();
  initRouting();
  initDebugTools();
  initRouteLabelSelector();

  // Routing area needs map style to be loaded
  if (map.isStyleLoaded()) {
    initRoutingArea();
  } else {
    map.on("load", () => initRoutingArea());
  }

  console.log("OSRM Inspector loaded successfully");
  hideLoading();
  verifyChanges();
});


/**
 * Initialize route label radio selector
 */
function initRouteLabelSelector() {
  const radios = document.querySelectorAll('input[name="route-label"]');
  radios.forEach((radio) => {
    radio.addEventListener("change", function () {
      const routeData = getCurrentRouteData();
      if (routeData) {
        addRouteLabels(routeData, this.value);
      }
    });
  });
}

/**
 * Verify OSRM Inspector modifications have been applied correctly
 */
function verifyChanges() {
  console.log("Verifying OSRM Inspector modifications:");

  setTimeout(() => {
    try {
      const checks = {
        "Profile display": document.getElementById("profile-display"),
        "Algorithm display": document.getElementById("algorithm-display"),
        "Add waypoint btn": document.getElementById("btn-add-waypoint"),
        "CSV import btn": document.getElementById("btn-import-csv"),
        "Load URL btn": document.getElementById("btn-load-url"),
        "TD controls": document.getElementById("td-controls"),
        "Auto-update toggle": document.getElementById("auto-update-route"),
        "Edit profile btn": document.getElementById("btn-edit-profile"),
        "Route label options": document.getElementById("route-label-options"),
        "Results card": document.getElementById("card-results"),
        "Step info card": document.getElementById("card-step-info"),
        "Debug buttons": document.getElementById("btn-show-nodes"),
        "Routing area load": document.getElementById("btn-load-routing-area"),
        "Routing area toggle": document.getElementById(
          "btn-toggle-routing-area"
        ),
      };

      Object.entries(checks).forEach(([name, el]) => {
        console.log(`${name}: ${el ? "\u2713" : "\u2717"}`);
      });

      console.log("All modifications applied successfully!");
    } catch (e) {
      console.error("Verification failed:", e);
    }
  }, 1000);
}
